services:
  db:
    container_name: postgres_database
    image: postgres:16.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    restart: always
    ports:
      - "5433:5432"

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.6
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=pgadmin@test.com
    restart: always

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/postgres
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always